server:
    port: 8080
spring:
    application:
        name: Elearning
    datasource:
        url: jdbc:mysql://localhost:3306/elearning
        username: root
        password: hoangvinh99
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    data:
        jdbc:
            dialect: mysql

open:
    api:
        title: Api E-learning Document
        version: v1.0.0
        description: E-learning Document
        serverName: Sever Test
        serverUrl: http://localhost:8080
